### 1.Create arrays with all the datatyps available in Numpy

### =>Numpy Data Types
* i -- integer
* b -- boolean
* u -- unsigned integer
* f -- float
* c -- complex float
* m -- timedelta
* M -- datetime
* O -- object
* S --- string
* U -- unicode string
* V -- fixed chunk of memory for other type ( void )

In [3]:
import numpy as np
np.__version__

'1.16.4'

In [15]:
# 1.Integer Data Type
import numpy as np
arr=np.array([1,2,3,5,4],dtype='i')
arr.dtype

dtype('int32')

In [3]:
# 2.Boolean type
arr = np.array([1, 2, 3, 4], dtype='bool')

print(arr)
print(arr.dtype)

[ True  True  True  True]
bool


In [4]:
#3. Unsigned Integer type
arr = np.array([1, 2, 3, 4], dtype=np.uintc)

print(arr)
print(arr.dtype)

[1 2 3 4]
uint32


In [5]:
#4. Float type
arr = np.array([1, 2, 3, 4], dtype='f')

print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [6]:
#5. Complex float type
arr = np.array([1, 2, 3, 4], dtype=np.csingle)

print(arr)
print(arr.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex64


In [7]:
#6. Timedelta type
a=np.timedelta64(3,'D')
print(a)
a.dtype

3 days


dtype('<m8[D]')

In [8]:
#7. Date Time type
arr=np.array(['2005-02-25','2005-02-22','2006-03-25'],dtype='M')
print(arr)
print(arr.dtype)


['2005-02-25' '2005-02-22' '2006-03-25']
datetime64[D]


In [10]:
#8. Object type
arr = np.array([1, 2, 3, 4], dtype='O')

print(arr)
print(arr.dtype)

[1 2 3 4]
object


In [16]:
#9. String type
arr = np.array(["Likhitha", "CSE", "AI/ML"], dtype='S')

print(arr)
print(arr.dtype)

[b'Likhitha' b'CSE' b'AI/ML']
|S8


In [13]:
#10. Unicode String type
a=np.array([u'\u0394', u'\265Z', u'\265F', u'\u2202r'])
print(a)
print(a.dtype)

['Δ' 'µZ' 'µF' '∂r']
<U2


In [14]:
#11. Void
a=np.array([],dtype='V')
print(a)
print(a.dtype)

[]
|V8
